CREATE TABLE activity_programs (
  id                 serial,
  user_id            varchar(255),
  datetime           timestamp,
  start_time         varchar(4),
  end_time           varchar(4),
  practice_section   varchar(255),
  practice_Contents  varchar(255),
  venue_id           serial,
  route_id           serial,
  outward_trip       varchar(255),
  return_trip        varchar(255),
  contact_person1   varchar(255),
  contact_abstract1 varchar(255),
  contact_person2   varchar(255),
  contact_abstract2 varchar(255),
  create_time        timestamp default CURRENT_TIMESTAMP,
  update_time        timestamp default CURRENT_TIMESTAMP,
  CONSTRAINT activity_programs_PK PRIMARY KEY (id)
);