version: '3'
services:
  cmd:
    build: ./local/cmd
    container_name: local_cmd
    env_file:
      - .env
    environment: 
      GD_WORK_FOLDER: 1_C0EVIK-WeK0WSMF1eIDOXLkE6UhnmNJ
    tty: true
    volumes:
      - ./:/go/src
    working_dir: /go/src/app/cmd

