version: '3'
services:
  app:
    build: ./local/server
    container_name: local_app
    environment:
      DATABASE_URL: postgres://gwp:gwp@db:5432/gwp?sslmode=disable
      FRONT_URL: http://localhost:3000
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./:/go/src
    working_dir: /go/src
  cmd:
    build: ./local/cmd
    container_name: local_cmd
    env_file:
      - .env
    tty: true
    volumes:
      - ./:/go/src
    working_dir: /go/src/app/cmd 
  db:
    build: ./local/db
    container_name: local_db
    environment:
      POSTGRES_USER: gwp
      POSTGRES_PASSWORD: gwp
      POSTGRES_DB: gwp
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./local/db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./local/db/sql:/var/local
  migrate:
      build: ./migrate
      container_name: migrate
      environment:
        DATABASE_URL: postgres://gwp:gwp@db:5432/gwp?sslmode=disable
      tty: true
      volumes:
        - ./migrate:/var
      working_dir: /var

volumes:
  postgres-data:
