apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: app
build:
  artifacts:
  - image: waseda-covit19-docs-app
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths: ["./k8s/overlays/local"]
