apiVersion: v1
kind: Service
metadata:
  name: sample-lb
spec:
  type: NodePort  
  selector:
    app: sample-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
