name: Go

on:
  push:
    branches: [ deploy ]
#  pull_request:
#    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Heroku
      run: |
        echo Hello
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Deploy to Heroku
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        HEROKU_APP_NAME: waseda-covite19-docs
      run: |
        echo ${{ job.status }}
        echo ${{ github.ref }}
#      if: github.ref == 'refs/heads/main' && job.status == 'success'
#      run: |
#        git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/main:main
