name: Go

on:
  push:
    branches: [ deploy ]
#  pull_request:
#    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Heroku
      run: |
        echo Hello
