name: Go

on:
  push:
    branches: [ deploy ]
#  pull_request:
#    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Heroku
      run: |
        echo Hello
    - uses: actions/checkout@v1
    - run: git status
    - run: git branch -a
    - run: git push heroku main
    
