name: PullRequest

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  migrate-check:
    runs-on: ubuntu-latest
    steps:
    - name: Test PR
      run: |
        echo Hello PR
    - uses: actions/checkout@v2
    - name: Docker Compose Run
      shell: bash
      run: |
        make db-run
        docker-compose up -d migrate
    - name: Check Migrate Up
      shell: bash
      run: |
        docker exec migrate /bin/bash -c "bash migrate.bash up"
    - name: Check Migrate Down
      shell: bash
      run: |
        docker exec migrate /bin/bash -c "echo -y | bash migrate.bash down"
  go-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Go
      run: echo start go test
    - name: Docker Compose Run
      shell: bash
      run: |
        docker-compose up -d app
        docker exec local_app /bin/sh -c "go test ./..."
