name: Deploy

on:
  pull_request:
    branches: [ feature/add-pr-check ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Test PR
      run: |
        echo Hello PR
    - uses: actions/checkout@v2
    - name: compose-run
      shell: bash
      run: |
        make db-run
        exit 1


    

