name: Deploy

on:
  pull_request:
    branches: [ feature/add-pr-check ]

jobs:
  migrate-check:
    runs-on: ubuntu-latest
    steps:
    - name: Test PR
      run: |
        echo Hello PR
    - uses: actions/checkout@v2
    - name: compose-run
      shell: bash
      run: |
        make db-run
        docker-compose up -d migrate
        docker exec -it migrate /bin/bash -c 'ls'
    - name: migrate-up
      shell: bash
      run: |
        docker exec -it migrate /bin/bash -c 'false; echo $? > /tmp/return-code'
        exit $(docker exec local_db /bin/cat /tmp/return-code)



    

