name: Deploy

on:
  pull_request:
    branches: [ feature/add-pr-check ]

jobs:
  migrate-check:
    runs-on: ubuntu-latest
    steps:
    - name: Test PR
      run: |
        echo Hello PR
    - uses: actions/checkout@v2
    - name: compose-run
      shell: bash
      run: |
        make db-run
        docker-compose up -d migrate
    - name: migrate-up
      shell: bash
      run: |
        docker exec migrate /bin/bash -c "bash migrate.bash up"



    

